name: 'Google Bloaty Action'
description: 'Build and run google/bloaty on a set of files'
author: Kendal Harland

inputs:
  bloaty-version:
    description: A Git ref specifying the version of bloaty to build.
    default: 'refs/heads/main'
    required: false

  bloaty-checkout-dir:
    description: Where to clone and build google/bloaty
    default: ${{ github.workspace }}/.google-bloaty
    required: false

  bloaty-args:
    description: The arguments to pass to bloaty. Input filenames must use absolute paths.
    default: ''
    required: true

  bloaty-output-file:
    description: A filename where bloaty output should be written.
    default: 'bloaty-output'
    required: true

  cache-bloaty:
    description: Cache the bloaty executable for faster builds. The cache key is 'bloaty-<bloaty-version>'
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: Restore bloaty cache
      if: inputs.cache-bloaty == 'true'
      id: cache
      uses: actions/cache/restore@v3
      with:
        key: bloaty-${{ inputs.bloaty-version }}
        path: .caches/bloaty

    - name: Checkout google/bloaty
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: google/bloaty
        ref: ${{ inputs.bloaty-version }}
        path: ${{ inputs.bloaty-checkout-dir }}
        show-progress: false

    - name: Setup Ninja
      if: steps.cache.outputs.cache-hit != 'true'
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Configure bloaty
      if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: cmake -B ${{ inputs.bloaty-checkout-dir }}/.build -S ${{ inputs.bloaty-checkout-dir }} -G Ninja

    - name: Build bloaty
      if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        cmake --build ${{ inputs.bloaty-checkout-dir }}/.build

        # Copy bloaty.exe to the same path used by the cache so we can add it to our PATH
        # in the next step, regardless of whether we hit the cache earlier.
        New-Item -Path .caches/bloaty -ItemType Directory -Force | Out-Null
        Copy-Item ${{ inputs.bloaty-checkout-dir }}/.build/bloaty.exe -Destination .caches/bloaty

    - name: Cache bloaty
      if: inputs.cache-bloaty == 'true' && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        key: bloaty-${{ inputs.bloaty-version }}
        path: .caches/bloaty

    - name: Add bloaty to path
      shell: pwsh
      run: echo ".caches/bloaty" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run bloaty
      shell: pwsh
      run: bloaty ${{ inputs.bloaty-args }} | Out-File ${{ inputs.bloaty-output-file }} -Encoding utf8
